//
//  LSIContactsController.m
//  Contacts-Hybrid
//
//  Created by David Wright on 6/2/20.
//  Copyright © 2020 Lambda, Inc. All rights reserved.
//

#import "LSIContactsController.h"

// Use the autogenerated Swift header for our classes
// Use _ for any -, special character, or space in the ProjectName
// #import "ProjectName-Swift.h"
#import "Contacts_Hybrid-Swift.h"

@interface LSIContactsController ()

@property (nonatomic) NSMutableArray *internalContacts;

@end

@implementation LSIContactsController

- (instancetype)init
{
    if (self = [super init]) {
        _internalContacts = [[NSMutableArray alloc] init];
        
        LSIContact *contact = [[LSIContact alloc] initWithName:@"David" relationship:@"Myself"];
        [_internalContacts addObject:contact];
    }
    return self;
}

- (NSArray *)contacts
{
    return _internalContacts.copy;
}

- (LSIContact *)contactAtIndex:(NSInteger)index
{
    return [_internalContacts objectAtIndex:index];
}

- (NSInteger)contactCount
{
    return _internalContacts.count;
}

@end
